feature: add support for multiple elements highlight
shipshapecode/shepherd pull request #2069
Opened 2022-09-16 04:29 UTC by IArny

I would propose feature to support multiple elements highlight. All elements selected with `attachTo.element ` will be highlighted if `attachTo.multiple` is `true`. I added `multiple` flag to `attachTo` field to keep old behavior. I'd appreciate your feedback for this PR.

2022-09-16 04:46 UTC, IArny commented
Also this PR can resolve https://github.com/shipshapecode/shepherd/issues/525 issue

2022-09-19 11:19 UTC, IArny commented
@rwwagner90  could you review this PR please

2022-09-22 07:10 UTC, IArny commented
@monshan Could you find a time for this PR?

2022-09-28 15:17 UTC, rwwagner90 requested changes

2022-09-28 15:17 UTC, rwwagner90 commented on index.html
> +            <div class=" bg-navy inline-block mb-4 w-56 lg:mr-4">
```suggestion
            <div class="bg-navy inline-block mb-4 w-56 lg:mr-4">
```

2022-09-28 15:17 UTC, rwwagner90 commented on landing/js/welcome.js
> +	  {
```suggestion
    {
```

2022-09-28 15:17 UTC, rwwagner90 commented on landing/js/welcome.js
> +		  on: 'bottom',
Lots of weird spacing issues in here. Could you please auto format this with prettier?

2022-09-28 15:17 UTC, rwwagner90 commented on src/js/components/shepherd-modal.svelte
> +      targetElements.forEach(el => {
Spacing issues here as well

2022-09-28 15:19 UTC, rwwagner90 commented
Thanks for the PR @IArny! Lots of formatting issues with the spacing in this code, please run prettier and clean things up and I will take another look. I think in general we would love to support this feature, but I am not sure if this is the best API for it.

2022-09-29 11:38 UTC, closed without merging

2022-09-30 06:16 UTC, IArny commented
@rwwagner90 thank you for your response. I closed this PR by mistake, but  already opened the new one https://github.com/shipshapecode/shepherd/pull/2083 . I ran prettier and it fixed a little bit more files than were changed by me, hope it's fine.