Allow arrow padding to be configured for a step.
shipshapecode/shepherd pull request #3051
Opened 2024-11-08 17:46 UTC by JakeThurman

Hi! First time contributer.

We have a >4px border radius on out shepherd-element, and our looking to increase it so the arrow doesn't overlay the border radius:
![image](https://github.com/user-attachments/assets/8dc120a6-2a1e-467f-a1ed-f0661b600ebd)

This PR allows you to configure the arrow padding using something like: `arrow: { padding: 10 }`

This builds and tests pass locally, please let me know if there's anything else you need from me on this PR, or anything I missed!

2024-12-05 16:05 UTC, JakeThurman commented
@RobbieTheWagner Any chance this could make it in soon? I'd rather not create an special fork for my company to use, and it sounds like this is important to have for us.

2025-01-28 14:40 UTC, RobbieTheWagner commented
Hi @JakeThurman apologies for the extremely late reply on this! Is this something that could be fixed via CSS in your app?

We do heavy arrow customization via CSS for our landing page with things like this:

```css
.shepherd-element[data-popper-placement^=top]>.shepherd-arrow {
  bottom:-8px
}
```

2025-01-28 15:11 UTC, JakeThurman commented
No worries on the delay. I appreciate you taking the time to reply now!

It's certainly possible, but it would only work in isolated cases. floating-ui has lots of logic to make sure the arrow points at the anchor element, and this would eliminate that down to just a fixed number of px from the edge. (i.e., middleware can shift the '
tour step 'balloon', but floating UI will adjust the arrow from there.)

This floating-ui padding parameter configures the closest the arrow can get to the edge of the balloon. It seems to be set to 4px because of the default shepherd CSS.

Finally, the floating-ui documentation explicitly says to set this parameter to your border-radius, which is what led me to open this PR so I could do so. See: https://floating-ui.com/docs/arrow#padding

2025-01-31 13:07 UTC, RobbieTheWagner requested changes
This is great work, thank you for taking this on! I just had a few minor suggestions.

2025-01-31 13:07 UTC, RobbieTheWagner commented on shepherd.js/src/utils/floating-ui.ts
> +
```suggestion
```

2025-01-31 13:07 UTC, RobbieTheWagner commented on shepherd.js/src/utils/floating-ui.ts
> +        arrow({ element: arrowEl, padding: hasEdgeAlignment ? arrowOptions.padding : 0 })
```suggestion
        arrow({ element: arrowEl, padding: hasEdgeAlignment ? step.options.arrow?.padding ?? 4 : 0 })
```

What would you think about putting this inline here? I think it is a little less verbose.

2025-01-31 13:07 UTC, RobbieTheWagner commented on test/unit/components/shepherd-element.spec.js
> +        arrow: { padding: 10 },
Thanks for adding tests! Could we perhaps add an assertion checking that padding of `10px` is applied to the arrow element?

2025-01-31 13:07 UTC, RobbieTheWagner commented on test/unit/components/shepherd-element.spec.js
> +      expect(
For this one, perhaps we could also assert padding, and I think it would be `0px` here?

2025-02-05 16:40 UTC, JakeThurman commented
Pushed a fixup for the requested changes. I wasn't able to run my updated tests... 

I know I did originally when opening this PR, but I couldn't remember how to run them now. 
(I tried `pnpm run test:ci` didn't seem to work -- I got "No projects matched the filters in "C:\projects\shepherd")
Is that the right command?

2025-02-19 18:09 UTC, RobbieTheWagner commented
@JakeThurman apologies for the delay on this! The commands you will want to run tests are from the root: `pnpm test:cy:watch` or `pnpm test:unit:watch`

2025-02-19 19:33 UTC, JakeThurman commented
> test:cy:watch

Thanks! Updated my fixup to get the tests working.

2025-02-20 16:18 UTC, RobbieTheWagner commented
Thanks @JakeThurman I think things are looking good now! One final request, could you please update the docs to mention this? The auto generated docs will be updated based on your comments, but we have some hand rolled docs too like https://github.com/shipshapecode/shepherd/blob/main/docs-src/src/content/docs/guides/usage.md#-displaying-arrows

2025-02-20 16:43 UTC, JakeThurman commented
> Thanks @JakeThurman I think things are looking good now! One final request, could you please update the docs to mention this? The auto generated docs will be updated based on your comments, but we have some hand rolled docs too like [`main`/docs-src/src/content/docs/guides/usage.md#-displaying-arrows](https://github.com/shipshapecode/shepherd/blob/main/docs-src/src/content/docs/guides/usage.md#-displaying-arrows)

Done. I did a grep and didn't find any other documentation that appeared to need updating.

2025-02-20 17:16 UTC, RobbieTheWagner commented on shepherd.js/src/utils/floating-ui.ts
> +
```suggestion
```

2025-02-20 17:17 UTC, RobbieTheWagner commented on shepherd.js/src/utils/floating-ui.ts
> +          padding: hasEdgeAlignment ? arrowOptions.padding : 0
```suggestion
          padding: hasEdgeAlignment ? step.options.arrow?.padding ?? 4 : 0
```

2025-02-20 17:18 UTC, RobbieTheWagner commented
Thanks @JakeThurman! I think my suggestions might have gotten lost from before. I left a couple more, please let me know what you think of them.

2025-02-20 18:01 UTC, JakeThurman commented on shepherd.js/src/utils/floating-ui.ts
> +          padding: hasEdgeAlignment ? arrowOptions.padding : 0
I think this would be working javascript (I.e., `(true).padding` is `undefined`) but typescript doesn't allow that.

2025-02-20 18:09 UTC, RobbieTheWagner commented on shepherd.js/src/utils/floating-ui.ts
> +          padding: hasEdgeAlignment ? arrowOptions.padding : 0
Oh, gotcha. Didn't realize TS wouldn't allow it.

2025-02-20 18:09 UTC, RobbieTheWagner approved these changes

2025-02-20 18:09 UTC, merged